actions:
  get-current-version:
    - "python3 ./setup.py --version"
  create-archive:
    - "make local"
    - 'bash -c "ls *.tar*"'

jobs:
# Fedora builds for the 'master' branch
- job: copr_build
  targets:
    - fedora-all
  trigger: pull_request
  branch: master

# Downstream builds
- job: propose_downstream
  trigger: release
  dist_git_branches:
    - fedora-all

- job: koji_build
  trigger: commit
  dist_git_branches:
    - fedora-all

- job: bodhi_update
  trigger: commit
  dist_git_branches:
    - fedora-branched

srpm_build_deps:
 - make
 - python3-devel
 - python3-setuptools
 - python3-build

downstream_package_name: python-pocketlint
